/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1.de.estructuras_graphstream;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.File;
import java.util.Set;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.view.Viewer;
/**
 *
 * @author andre
 * @author Santiago Hernandez
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    private static final int MAX_NODOS = 2000;

    private Grafo grafoActual;
    private String rutaGrafoActual;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        grafoActual = null;
        rutaGrafoActual = null;
        this.setResizable(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CambiarGrafo = new javax.swing.JDialog();
        AgregarProteina = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        EliminarProteina = new javax.swing.JButton();
        Salir2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CargarRedDeProteinas = new javax.swing.JButton();
        Dijkstra = new javax.swing.JButton();
        Hubs = new javax.swing.JButton();
        VisualizarGrafo = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        ModificarGrafo = new javax.swing.JButton();
        Salir1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DeteccionComp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        AgregarProteina.setText("Agregar Proteina");
        AgregarProteina.addActionListener(this::AgregarProteinaActionPerformed);

        jLabel2.setText("Modificar Grafo");

        EliminarProteina.setText("Eliminar Proteina");
        EliminarProteina.addActionListener(this::EliminarProteinaActionPerformed);

        Salir2.setText("Salir");
        Salir2.setAlignmentY(0.8F);
        Salir2.addActionListener(this::Salir2ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout CambiarGrafoLayout = new javax.swing.GroupLayout(CambiarGrafo.getContentPane());
        CambiarGrafo.getContentPane().setLayout(CambiarGrafoLayout);
        CambiarGrafoLayout.setHorizontalGroup(
            CambiarGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiarGrafoLayout.createSequentialGroup()
                .addGroup(CambiarGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CambiarGrafoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(CambiarGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarProteina)
                            .addComponent(AgregarProteina))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CambiarGrafoLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(CambiarGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salir2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        CambiarGrafoLayout.setVerticalGroup(
            CambiarGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CambiarGrafoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(CambiarGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CambiarGrafoLayout.createSequentialGroup()
                        .addComponent(AgregarProteina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliminarProteina))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(Salir2)
                .addGap(36, 36, 36))
        );

        jButton1.setText("Eliminar Nodo ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(610, 309));
        setPreferredSize(new java.awt.Dimension(1000, 309));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Caracteristicas del programa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        CargarRedDeProteinas.setText("Cargar Red De Proteinas");
        CargarRedDeProteinas.addActionListener(this::CargarRedDeProteinasActionPerformed);
        getContentPane().add(CargarRedDeProteinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 20));

        Dijkstra.setText("Calcular Ruta Metabolica");
        Dijkstra.addActionListener(this::DijkstraActionPerformed);
        getContentPane().add(Dijkstra, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 230, 20));

        Hubs.setText("Indentificar Hubs");
        Hubs.setMaximumSize(new java.awt.Dimension(211, 23));
        Hubs.addActionListener(this::HubsActionPerformed);
        getContentPane().add(Hubs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 20));

        VisualizarGrafo.setText("Visualizar Grafo");
        VisualizarGrafo.addActionListener(this::VisualizarGrafoActionPerformed);
        getContentPane().add(VisualizarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 170, 20));

        Guardar.setText("Guardar Cambios");
        Guardar.addActionListener(this::GuardarActionPerformed);
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 250, 40));

        ModificarGrafo.setText("Modificar Grafo");
        ModificarGrafo.addActionListener(this::ModificarGrafoActionPerformed);
        getContentPane().add(ModificarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 170, 20));

        Salir1.setText("Salir");
        Salir1.addActionListener(this::Salir1ActionPerformed);
        getContentPane().add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 130, 40));

        jLabel4.setText("Status");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 293, 172, -1));

        DeteccionComp.setText("Deteccion de Complejos proteicos");
        DeteccionComp.addActionListener(this::DeteccionCompActionPerformed);
        getContentPane().add(DeteccionComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 230, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 980, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    * metodo para visualizar el grafo usando graphstream
    */
    private void VisualizarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarGrafoActionPerformed
        // se verifica si hay un grafo cargado
        if (grafoActual == null) {
            jLabel4.setText("No hay grafo cargado para visualizar.");
            return;
        }

        // se obtiene el primer nodo para validar que el grafo no este vacio
        Nodo primero = ManejoDeArchivos.obtenerPrimero(grafoActual);
        if (primero == null) {
            jLabel4.setText("El grafo está vacío.");
            return;
        }
        
        // se configura graphstream para que funcione con swing
        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("Red de proteinas");

        // se define el estilo visual de los nodos y arcos
        String desing =
                "node{"
                + " fill-color: #3498db;"
                + " size: 25px;"
                + " text-size: 14px;"
                + " text-color: #2c3e50;"
                + " text-alignment: at-right;"
                + " text-offset: 8px, 0px;"
                + " text-background-mode: plain;"
                + " text-background-color: rgba(255, 255, 255, 200);"
                + " text-padding: 3px;"
                + "}"
                + "edge{"
                + " fill-color: #bdc3c7;"
                + " text-size: 11px;"
                + " text-color: #7f8c8d;"
                + "}";
        graph.setAttribute("ui.stylesheet", desing);
        graph.setAttribute("ui.antialias");
        graph.setAttribute("layout.force", 0.5);
        graph.setAttribute("layout.quality", 4);
        
        // se recorren todos los nodos del grafo para crearlos en graphstream
        for (Nodo origen = primero; origen != null; origen = origen.pNext){
            String nombreOrigen = ManejoDeArchivos.nombreNodo(origen);
            
            // si el nodo no existe en graphstream, se crea
            if(graph.getNode(nombreOrigen) == null){
                Node n = graph.addNode(nombreOrigen);
                n.setAttribute("ui.label", nombreOrigen);
            }
            
            // se recorren todos los arcos del nodo origen
            Arco arco = origen.lista.ObtenerPrimero();
            while(arco != null){
                Nodo destino = arco.getDestino();
                String nombreDestino = ManejoDeArchivos.nombreNodo(destino);
                double peso = arco.getPeso();
                
                // si el nodo destino no existe, se crea
                if(graph.getNode(nombreDestino) == null){
                    Node n = graph.addNode(nombreDestino);
                    n.setAttribute("ui.label", nombreDestino);
                }
                
                // se crea un id unico para el arco para evitar duplicados
                String idArco;
                if (nombreOrigen.compareTo(nombreDestino) < 0){
                    idArco = nombreOrigen + "-" + nombreDestino;
                } else{
                    idArco = nombreDestino + "-" + nombreOrigen;
                }
                
                // si el arco no existe, se crea con su peso
                if (graph.getEdge(idArco) == null){
                    Edge e = graph.addEdge(idArco, nombreOrigen, nombreDestino, false);
                    e.setAttribute("ui.label", String.valueOf(peso));
                }
                arco = arco.ObtenerpNext();
            }
        }
        
    
       org.graphstream.ui.view.Viewer viewer = new org.graphstream.ui.swing_viewer.SwingViewer(graph, org.graphstream.ui.view.Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
       viewer.enableAutoLayout();
       
       org.graphstream.ui.swing_viewer.ViewPanel viewPanel = (org.graphstream.ui.swing_viewer.ViewPanel) viewer.addDefaultView(false);
       // Configuracion del contenedor en la interfaz Swing
       if (jPanel1 != null) {
           jPanel1.removeAll();
           jPanel1.setLayout(new java.awt.BorderLayout());
           jPanel1.add(viewPanel, java.awt.BorderLayout.CENTER);

           jPanel1.revalidate();
           jPanel1.repaint();
           jLabel1.setText("Grafo visualizado en el panel principal.");
       } else {
           
           graph.display(); 
           jLabel2.setText("Error: panelGrafo no encontrado. Abriendo ventana externa.");
       }
    }//GEN-LAST:event_VisualizarGrafoActionPerformed

    /**
     * metodo para calcular la ruta mas corta entre dos proteinas usando dijkstra
     */
    private void DijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DijkstraActionPerformed
        // se verifica si hay un grafo cargado
        if (grafoActual == null) {
            jLabel4.setText("Debe cargar un grafo antes de calcular la ruta.");
            return;
        }

        // se pide al usuario el nombre de la proteina de origen
        String origenNombre = JOptionPane.showInputDialog(this, "Nombre de la proteína origen:");
        if (origenNombre == null || origenNombre.trim().isEmpty()) {
            return;
        }
        
        // se pide al usuario el nombre de la proteina de destino
        String destinoNombre = JOptionPane.showInputDialog(this, "Nombre de la proteína destino:");
        if (destinoNombre == null || destinoNombre.trim().isEmpty()) {
            return;
        }

        // se buscan los nodos en el grafo
        Nodo origen = buscarNodoPorNombre(grafoActual, origenNombre.trim());
        Nodo destino = buscarNodoPorNombre(grafoActual, destinoNombre.trim());

        // se verifica que ambas proteinas existan
        if (origen == null || destino == null) {
            jLabel4.setText("Alguna de las proteínas no existe en el grafo.");
            return;
        }

        // se calcula la ruta mas corta usando el algoritmo dijkstra
        ListaAuxiliar ruta = grafoActual.Dijkstra(origen, destino);
        if (ruta == null) {
            jLabel4.setText("No se pudo calcular la ruta.");
            return;
        }

        // se convierte la ruta a texto para mostrarla
        String textoRuta = rutaComoTexto(ruta, destino);
        if (textoRuta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No existe ruta entre las proteínas seleccionadas.", "Sin Ruta", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // se obtiene la distancia total de la ruta
        double distancia = destino.ObtenerDistanciaMinima();
        String mensaje = "Ruta encontrada:\n" + textoRuta + "\n\nDistancia total: " + distancia;
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Ruta Metabólica Calculada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        jLabel1.setText("Ruta calculada: " + origenNombre + " -> " + destinoNombre);
        jLabel4.setText("");
    }//GEN-LAST:event_DijkstraActionPerformed

    /**
     *  metodo para encontrar la proteina con mas conexiones (hub)
     */
    private void HubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HubsActionPerformed
        // se verifica si hay un grafo cargado
        if (grafoActual == null) {
            jLabel4.setText("Debe cargar un grafo antes de identificar Hubs.");
            return;
        }

        // se obtiene el primer nodo para validar que el grafo no este vacio
        Nodo primero = obtenerPrimero(grafoActual);
        if (primero == null) {
            jLabel4.setText("El grafo está vacío.");
            return;
        }

        // variables para guardar el nodo con mayor grado (mas conexiones)
        Nodo mejor = null;
        int mejorGrado = -1;

        // se recorren todos los nodos del grafo
        for (Nodo n = primero; n != null; n = n.pNext) {
            int grado = n.ObtenerGrado();
            // si este nodo tiene mas conexiones que el mejor actual, se actualiza
            if (grado > mejorGrado) {
                mejorGrado = grado;
                mejor = n;
            }
        }

        // si no se encontro ningun nodo, se muestra mensaje de error
        if (mejor == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún Hub en el grafo.", "Sin Hubs", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // se obtiene el nombre del hub encontrado
        String nombre = nombreNodo(mejor);
        String mensaje = "Hub principal encontrado:\n\nProteína: " + nombre + "\nGrado: " + mejorGrado + "\n\nEl grado representa el número de conexiones directas que tiene esta proteína con otras en la red.";
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Hub Identificado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        jLabel1.setText("Hub identificado: " + nombre);
        jLabel4.setText("");
    }//GEN-LAST:event_HubsActionPerformed

    private void ModificarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarGrafoActionPerformed
        if (grafoActual == null) {
            jLabel4.setText("Debe cargar un grafo antes de modificarlo.");
            return;
        }

        jTextArea1.setText("");
        CambiarGrafo.pack();
        CambiarGrafo.setLocationRelativeTo(this);
        CambiarGrafo.setVisible(true);
    }//GEN-LAST:event_ModificarGrafoActionPerformed

    private void Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir1ActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
    }//GEN-LAST:event_Salir1ActionPerformed

    /**
     * metodo para agregar una nueva proteina al grafo
     */
    private void AgregarProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProteinaActionPerformed
        // se verifica si hay un grafo cargado
        if (grafoActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe cargar un grafo antes de agregar proteínas.");
            return;
        }

        // se pide al usuario el nombre de la nueva proteina
        String texto = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre de la nueva proteina:", "Agregar Proteina", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (texto == null || texto.trim().isEmpty()) {
            return;
        }
        texto = texto.trim();
        
        // se verifica si la proteina ya existe en el grafo
        if(buscarProteinaEnGrafo(texto) != null){
            javax.swing.JOptionPane.showMessageDialog(this, "La proteina " + texto + " ya existe en el grafo.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            jTextArea1.append("[-] Fallo al agregar: " + texto + " (ya existe)\n");
        } else{
            // se añade la nueva proteina al grafo
            grafoActual.AgregarNodo(texto);
            jTextArea1.append("[+] Agregada: " + texto + "\n");
            jLabel1.setText("Proteina " + texto + " Agregada con exito");
            jLabel4.setText("");
        }
    }//GEN-LAST:event_AgregarProteinaActionPerformed

    /**
     * metodo para agregar un arco entre dos nodos con un peso
     */
    private void agregararcobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregararcobotonActionPerformed
        // se verifica si hay un grafo cargado
        if (grafoActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe cargar un grafo antes de agregar arcos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // se pide al usuario el nombre del nodo origen
        String nodoOrigen = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre del nodo origen:", "Agregar Arco", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (nodoOrigen == null || nodoOrigen.trim().isEmpty()) {
            return;
        }
        nodoOrigen = nodoOrigen.trim();

        // se pide al usuario el nombre del nodo destino
        String nodoDestino = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre del nodo destino:", "Agregar Arco", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (nodoDestino == null || nodoDestino.trim().isEmpty()) {
            return;
        }
        nodoDestino = nodoDestino.trim();

        // se pide al usuario el peso del arco
        String pesoStr = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el peso del arco:", "Agregar Arco", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (pesoStr == null || pesoStr.trim().isEmpty()) {
            return;
        }

        try {
            // se convierte el peso a numero
            double peso = Double.parseDouble(pesoStr.trim());
            
            // se buscan los nodos en el grafo
            Nodo origen = buscarProteinaEnGrafo(nodoOrigen);
            Nodo destino = buscarProteinaEnGrafo(nodoDestino);
            
            // se verifica que el nodo origen exista
            if (origen == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "El nodo origen '" + nodoOrigen + "' no existe en el grafo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // se verifica que el nodo destino exista
            if (destino == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "El nodo destino '" + nodoDestino + "' no existe en el grafo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // se crea el arco entre los dos nodos
            grafoActual.AgregarArco(origen, destino, peso);
            javax.swing.JOptionPane.showMessageDialog(this, "Arco agregado exitosamente:\n" + nodoOrigen + " -> " + nodoDestino + " (peso: " + peso + ")", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            jTextArea1.append("[+] Arco agregado: " + nodoOrigen + " -> " + nodoDestino + " (peso: " + peso + ")\n");
            jLabel1.setText("Arco agregado: " + nodoOrigen + " -> " + nodoDestino);
            jLabel4.setText("");
            
        } catch (NumberFormatException e) {
            // si el peso no es un numero valido, se muestra error
            javax.swing.JOptionPane.showMessageDialog(this, "El peso debe ser un número válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregararcobotonActionPerformed
    /**
     * Metodo para el boton eliminar proteina.
     */
    private void EliminarProteinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProteinaActionPerformed
        if (grafoActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe cargar un grafo antes de eliminar proteínas.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombreProteina = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el nombre de la proteína a eliminar:", "Eliminar Proteína", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (nombreProteina == null || nombreProteina.trim().isEmpty()) {
            return;
        }
        nombreProteina = nombreProteina.trim();

        Nodo nodoAEliminar = buscarProteinaEnGrafo(nombreProteina);
        if (nodoAEliminar == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "La proteína '" + nombreProteina + "' no existe en el grafo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Desea eliminar también los arcos asociados a esta proteína?", 
            "Eliminar Arcos", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE);
        
        boolean eliminarArcos = (respuesta == javax.swing.JOptionPane.YES_OPTION);

        String[] nombresAEliminar = {nombreProteina};

        Grafo nuevo = new Grafo();
        Nodo[] viejos = new Nodo[MAX_NODOS];
        Nodo[] nuevos = new Nodo[MAX_NODOS];
        int cantidadNodos = 0;

        Nodo primero = obtenerPrimero(grafoActual);
        for (Nodo n = primero; n != null && cantidadNodos < MAX_NODOS; n = n.pNext) {
            String nombre = nombreNodo(n);
            if (!estaEnLista(nombre, nombresAEliminar, nombresAEliminar.length)) {
                Nodo nuevoNodo = nuevo.AgregarNodo(nombre);
                viejos[cantidadNodos] = n;
                nuevos[cantidadNodos] = nuevoNodo;
                cantidadNodos++;
            }
        }

        for (int i = 0; i < cantidadNodos; i++) {
            Nodo viejoOrigen = viejos[i];
            Nodo nuevoOrigen = nuevos[i];
            Arco arco = viejoOrigen.lista.ObtenerPrimero();
            while (arco != null) {
                Nodo viejoDestino = arco.getDestino();
                int j = indiceDeNodo(viejoDestino, viejos, cantidadNodos);
                if (j != -1 && i <= j) {
                    Nodo nuevoDestino = nuevos[j];
                    double peso = arco.getPeso();
                    nuevo.AgregarArco(nuevoOrigen, nuevoDestino, peso);
                }
                arco = arco.ObtenerpNext();
            }
        }

        grafoActual = nuevo;
        String mensaje = eliminarArcos ? 
            "Proteína '" + nombreProteina + "' y sus arcos eliminados exitosamente." : 
            "Proteína '" + nombreProteina + "' eliminada exitosamente.";
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        jTextArea1.append("[-] Eliminada: " + nombreProteina + "\n");
        jLabel1.setText("Proteína eliminada: " + nombreProteina);
        jLabel4.setText("");
    }//GEN-LAST:event_EliminarProteinaActionPerformed

    private void Salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir2ActionPerformed
        CambiarGrafo.setVisible(false);
    }//GEN-LAST:event_Salir2ActionPerformed
    /**
     * Metodo que enlaza la clase ManejoDeArchivos para su uso en Principal 
     */
    private void CargarRedDeProteinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarRedDeProteinasActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filtro = new javax.swing.filechooser.FileNameExtensionFilter("Archivos CSV (*.csv)", "csv"); // solo muestra archivos CSV en la ventana de busqueda
        chooser.setFileFilter(filtro);
        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = chooser.getSelectedFile();
            String nombreArchivo = archivo.getName().toLowerCase();
            
            if(!nombreArchivo.endsWith(".csv")){ // condicional de verificacion si es o no es un archivo CSV
                jLabel1.setText("Sin grafo cargado.");
                jLabel4.setText("Error: el archivo debe ser en formato CSV.");
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un archivo de extension .csv", "Archivo no valido",javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            Grafo g = ManejoDeArchivos.cargarGrafo(archivo.getAbsolutePath());
            if (g != null) {
                grafoActual = g;
                rutaGrafoActual = archivo.getAbsolutePath();
                jLabel1.setText("Grafo cargado: " + archivo.getName());
                jLabel4.setText("");
            } else {
                jLabel1.setText("Sin grafo cargado.");
                jLabel4.setText("Error al cargar el grafo: " + archivo.getName());
            }
        }
        
    }//GEN-LAST:event_CargarRedDeProteinasActionPerformed

    /**
     * metodo para guardar los cambios del grafo en un archivo csv
     */
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // se verifica si hay un grafo para guardar
        if (grafoActual == null) {
            jLabel4.setText("No hay grafo para guardar.");
            return;
        }

        // se crea la carpeta archivos csv si no existe
        File carpetaCsv = new File("archivos csv");
        if (!carpetaCsv.exists()) {
            carpetaCsv.mkdirs();
        }

        // se genera un nombre de archivo unico con timestamp
        String timestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String nombreArchivo = "grafo_" + timestamp + ".csv";
        File archivo = new File(carpetaCsv, nombreArchivo);
        
        // se guarda el grafo en el archivo csv
        ManejoDeArchivos.modificarGrafo(archivo.getAbsolutePath(), grafoActual);
        
        // se actualiza la ruta actual y se muestra mensaje de confirmacion
        rutaGrafoActual = archivo.getAbsolutePath();
        jLabel1.setText("Grafo guardado en: " + archivo.getName());
        jLabel4.setText("Archivo guardado en carpeta 'archivos csv'");
        javax.swing.JOptionPane.showMessageDialog(this, "Grafo guardado exitosamente en:\n" + archivo.getAbsolutePath(), "Guardado Exitoso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Metodo que usa DFS para la deteccion de complejos proteicos.
     */
    private void DeteccionCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeteccionCompActionPerformed
        // TODO add your handling code here:
        if (grafoActual == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe cargar un grafo primero.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        grafoActual.ReiniciarVisitados();

        StringBuilder reporte = new StringBuilder("DETECCIÓN DE COMPLEJOS PROTEICOS\n");

        int cantidadComplejos = 0;
        int proteinasTotales = 0;

        Nodo nodoIterador = ManejoDeArchivos.obtenerPrimero(grafoActual);

        while (nodoIterador != null) {
            if (!nodoIterador.esVisitado()) {
                cantidadComplejos++;

                ListaAuxiliar complejo = grafoActual.DFS(nodoIterador);

                reporte.append("Complejo #").append(cantidadComplejos).append(":\n > ");

                NodoAuxiliar aux = complejo.pFirst;
                while (aux != null) {
                    proteinasTotales++;

                    String nombre = ManejoDeArchivos.nombreNodo(aux.proteina);
                    reporte.append("[").append(nombre).append("]");

                    if (aux.pNextAuxiliar != null) {
                        reporte.append(" -> ");
                    }

                    aux.proteina.AgregarVisitado(true);
                    aux = aux.pNextAuxiliar;
                }
                reporte.append("\n\n");
            }
            nodoIterador = nodoIterador.pNext;
        }

        reporte.append("Total de complejos: ").append(cantidadComplejos).append("\n");
        reporte.append("Total de proteínas analizadas: ").append(proteinasTotales);

        javax.swing.JOptionPane.showMessageDialog(this, reporte.toString(), "Análisis de Componentes Conexos", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        jLabel1.setText("Complejos: " + cantidadComplejos);
        jTextArea1.append("[Análisis] Se detectaron " + cantidadComplejos + " grupos independientes.\n");
    }//GEN-LAST:event_DeteccionCompActionPerformed

    // --- Métodos auxiliares privados ---

    private Nodo obtenerPrimero(Grafo grafo) {
        try {
            java.lang.reflect.Field f = Grafo.class.getDeclaredField("pFirst");
            f.setAccessible(true);
            return (Nodo) f.get(grafo);
        } catch (Exception e) {
            return null;
        }
    }

    private String nombreNodo(Nodo n) {
        if (n == null) return "";
        Object d = n.dato;
        if (d == null) return "";
        return String.valueOf(d).trim();
    }

    private Nodo buscarNodoPorNombre(Grafo grafo, String nombre) {
        Nodo primero = obtenerPrimero(grafo);
        for (Nodo n = primero; n != null; n = n.pNext) {
            if (nombre.equals(nombreNodo(n))) {
                return n;
            }
        }
        return null;
    }

    private String rutaComoTexto(ListaAuxiliar ruta, Nodo destino) {
        try {
            java.lang.reflect.Field f = ListaAuxiliar.class.getDeclaredField("pFirst");
            f.setAccessible(true);
            Object auxObj = f.get(ruta);
            if (!(auxObj instanceof NodoAuxiliar)) {
                return "";
            }
            NodoAuxiliar aux = (NodoAuxiliar) auxObj;

            String[] nombres = new String[MAX_NODOS];
            int cantidad = 0;
            while (aux != null && cantidad < MAX_NODOS) {
                Nodo n = aux.proteina;
                nombres[cantidad++] = nombreNodo(n);
                aux = aux.pNextAuxiliar;
            }

            if (cantidad == 0) {
                return "";
            }

            StringBuilder sb = new StringBuilder();
            for (int i = cantidad - 1; i >= 0; i--) {
                if (sb.length() > 0) {
                    sb.append(" -> ");
                }
                sb.append(nombres[i]);
            }
            return sb.toString();
        } catch (Exception e) {
            return "";
        }
    }

    private boolean estaEnLista(String nombre, String[] lista, int cantidad) {
        for (int i = 0; i < cantidad; i++) {
            if (nombre.equals(lista[i])) {
                return true;
            }
        }
        return false;
    }

    private int indiceDeNodo(Nodo buscado, Nodo[] lista, int cantidad) {
        for (int i = 0; i < cantidad; i++) {
            if (lista[i] == buscado) {
                return i;
            }
        }
        return -1;
    }
    
    private Nodo buscarProteinaEnGrafo(String nombre){
        Nodo actual = ManejoDeArchivos.obtenerPrimero(grafoActual);
        while(actual != null){
            if(ManejoDeArchivos.nombreNodo(actual).equalsIgnoreCase(nombre)){
                return actual;
            }
            actual = actual.pNext;
        }
        return null;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarProteina;
    private javax.swing.JDialog CambiarGrafo;
    private javax.swing.JButton CargarRedDeProteinas;
    private javax.swing.JButton DeteccionComp;
    private javax.swing.JButton Dijkstra;
    private javax.swing.JButton EliminarProteina;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Hubs;
    private javax.swing.JButton ModificarGrafo;
    private javax.swing.JButton Salir1;
    private javax.swing.JButton Salir2;
    private javax.swing.JButton VisualizarGrafo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
//